version: '3.8'

services:
  guardrag:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLM_ENDPOINT=http://ollama:11434/v1
      - LLM_API_KEY=ollama
      - LLM_MODEL=qwen2.5:latest
      - COLPALI_MODEL=vidore/colqwen2.5-v0.2
      - ENABLE_INPUT_GUARDRAILS=true
      - ENABLE_OUTPUT_GUARDRAILS=true
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
  qdrant_storage:
